import type { NextPage } from 'next'
import Head from 'next/head'
import Home from '@screens/Home';

const HomePage: NextPage = () => {
  return (
    <div className="bg-primary flex items-center justify-center min-h-screen relative">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Home />
    </div>
  )
}

export default HomePage
